FROM python:3.9-slim

WORKDIR /moja_apka

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY text_model.pkl .
COPY text_vectorizer.pkl .
COPY webapp.py .
COPY templates/ ./templates/

EXPOSE 4001

CMD ["python", "webapp.py"]